defmodule Ledgr.Domains.HelloDoctor.PatientsTest do
  use Ledgr.DataCase, async: true

  alias Ledgr.Domains.HelloDoctor.Patients
  alias Ledgr.Domains.HelloDoctor.Patients.Patient

  setup do
    Ledgr.Repo.put_active_repo(Ledgr.Repos.HelloDoctor)
    Ledgr.Domain.put_current(Ledgr.Domains.HelloDoctor)
    :ok
  end

  defp patient_fixture(attrs \\ %{}) do
    attrs =
      %{
        "full_name" => "Jane Doe #{System.unique_integer([:positive])}",
        "phone" => "+52155500#{System.unique_integer([:positive])}",
        "display_name" => "Jane"
      }
      |> Map.merge(Map.new(attrs, fn {k, v} -> {to_string(k), v} end))

    {:ok, patient} = Patients.create_patient(attrs)
    patient
  end

  describe "create_patient/1" do
    test "inserts with autogenerated id when absent" do
      {:ok, p} = Patients.create_patient(%{"full_name" => "Ada", "phone" => "555-0001"})
      assert is_binary(p.id)
      assert p.full_name == "Ada"
    end

    test "accepts a caller-provided id" do
      id = Ecto.UUID.generate()
      {:ok, p} = Patients.create_patient(%{"id" => id, "full_name" => "Ben"})
      assert p.id == id
    end
  end

  describe "get_patient!/1" do
    test "returns the patient with preloaded associations" do
      p = patient_fixture()
      loaded = Patients.get_patient!(p.id)

      assert loaded.id == p.id
      assert is_list(loaded.consultations)
      assert is_list(loaded.medical_records)
    end

    test "raises for an unknown id" do
      assert_raise Ecto.NoResultsError, fn ->
        Patients.get_patient!(Ecto.UUID.generate())
      end
    end
  end

  describe "update_patient/2 + delete_patient/1" do
    test "update_patient/2 changes a field" do
      p = patient_fixture()
      {:ok, updated} = Patients.update_patient(p, %{"full_name" => "New Name"})
      assert updated.full_name == "New Name"
    end

    test "delete_patient/1 removes the row" do
      p = patient_fixture()
      assert {:ok, _} = Patients.delete_patient(p)

      assert_raise Ecto.NoResultsError, fn ->
        Patients.get_patient!(p.id)
      end
    end

    test "change_patient/2 returns a changeset" do
      p = patient_fixture()
      assert %Ecto.Changeset{} = Patients.change_patient(p, %{"full_name" => "X"})
    end
  end

  describe "list_patients/1" do
    test "returns all patients" do
      p1 = patient_fixture()
      p2 = patient_fixture()

      ids = Patients.list_patients() |> Enum.map(& &1.id)
      assert p1.id in ids
      assert p2.id in ids
    end

    test "filters by search on full_name" do
      p =
        patient_fixture(%{
          "full_name" => "Rare Unique Name #{System.unique_integer([:positive])}"
        })

      _other = patient_fixture()

      results = Patients.list_patients(search: "Rare Unique")
      assert Enum.any?(results, &(&1.id == p.id))
      assert length(results) >= 1
    end

    test "empty search string is ignored (returns everything)" do
      p = patient_fixture()
      results = Patients.list_patients(search: "")
      assert Enum.any?(results, &(&1.id == p.id))
    end
  end

  describe "patient_options/0" do
    test "returns {display_label, id} tuples" do
      p = patient_fixture()
      opts = Patients.patient_options()
      assert Enum.any?(opts, fn {_label, id} -> id == p.id end)
    end
  end

  describe "count_new/2" do
    test "counts patients created in range (inclusive)" do
      p = patient_fixture()
      today = Date.utc_today()

      n = Patients.count_new(today, today)
      assert n >= 1

      yesterday = Date.add(today, -1)
      n2 = Patients.count_new(yesterday, yesterday)
      # p is created today, shouldn't be counted for yesterday only
      refute p.id in (Patients.list_patients()
                      |> Enum.map(& &1.id)
                      |> Enum.filter(fn _ -> n2 > 0 end))

      assert is_integer(n2)
    end
  end

  describe "Patient.name/1" do
    test "prefers full_name" do
      assert Patient.name(%Patient{full_name: "Full", display_name: "Display"}) == "Full"
    end

    test "falls back to display_name" do
      assert Patient.name(%Patient{full_name: nil, display_name: "Display"}) == "Display"
    end

    test "falls back to Unknown" do
      assert Patient.name(%Patient{}) == "Unknown"
    end
  end
end
