import Config

# Configure databases (one per domain)
config :ledgr, Ledgr.Repos.MrMunchMe,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "ledgr_mr_munch_me_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  priv: "priv/repos/mr_munch_me"

config :ledgr, Ledgr.Repos.Viaxe,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "ledgr_viaxe_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  priv: "priv/repos/viaxe"

config :ledgr, Ledgr.Repos.VolumeStudio,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "ledgr_volume_studio_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  priv: "priv/repos/volume_studio"

config :ledgr, Ledgr.Repos.LedgrHQ,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "ledgr_ledgr_hq_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  priv: "priv/repos/ledgr_hq"

config :ledgr, Ledgr.Repos.CasaTame,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "ledgr_casa_tame_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  priv: "priv/repos/casa_tame"

# HelloDoctor + AMP repo config live at the END of this file (after
# dev.secret.exs loads), so a local `dev.secret.exs` can `System.put_env/2` the
# Neon URL before the env-var check runs. See the blocks below
# `import_config("dev.secret.exs")`.

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# Endpoint options that are serializable only (no MFAs or regexes).
# Watchers and live_reload are injected at runtime in Application.start/2
# so Mix can read the config (e.g. for releases or config tasks).
config :ledgr, LedgrWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "ByMeRIHNLQ3/aXlSPaJMGjooT9XPLGes39Tqnbyy4WO2j8aHR2PPXsFQA8R5Eocj"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :ledgr, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

config :ledgr, :prescrypto, enabled: false

# Load local secrets (Stripe keys, Neon URLs, etc.) — file is gitignored.
# Must come BEFORE the AMP repo config so a local secret can set
# AUMENTA_MI_PENSION_DATABASE_URL via System.put_env/2.
if File.exists?("config/dev.secret.exs"), do: import_config("dev.secret.exs")

# AMP dev DB.
#
# Default: local Postgres (`ledgr_aumenta_mi_pension_dev`) — fine for working on
# the Ledgr-owned tables (`users`, `accounts`, `journal_entries`, etc.).
#
# Override: set `AUMENTA_MI_PENSION_DATABASE_URL` (typically from
# `config/dev.secret.exs`) to point at a Neon dev branch. The bot-owned tables
# (`conversations`, `customers`, `messages`, …) only exist on Neon, so any view
# that queries them needs the override. See CLAUDE.md "Aumenta Mi Pensión —
# schema ownership" for the full table split.
if amp_url = System.get_env("AUMENTA_MI_PENSION_DATABASE_URL") do
  IO.puts(:stderr, "[dev.exs] AMP repo → Neon (#{URI.parse(amp_url).host})")

  config :ledgr, Ledgr.Repos.AumentaMiPension,
    url: amp_url,
    ssl: [
      verify: :verify_none,
      server_name_indication: to_charlist(URI.parse(amp_url).host || "")
    ],
    stacktrace: true,
    show_sensitive_data_on_connection_error: true,
    pool_size: 10,
    priv: "priv/repos/aumenta_mi_pension"
else
  IO.puts(
    :stderr,
    "[dev.exs] AMP repo → local Postgres (bot-owned tables WILL be missing; " <>
      "set AUMENTA_MI_PENSION_DATABASE_URL to use the Neon dev branch)"
  )

  config :ledgr, Ledgr.Repos.AumentaMiPension,
    username: "postgres",
    password: "postgres",
    hostname: "localhost",
    database: "ledgr_aumenta_mi_pension_dev",
    stacktrace: true,
    show_sensitive_data_on_connection_error: true,
    pool_size: 10,
    priv: "priv/repos/aumenta_mi_pension"
end

# HelloDoctor dev DB.
#
# Default: local Postgres (`ledgr_hello_doctor_dev`) — fine for the
# Ledgr-owned/managed tables (`doctors`, etc.).
#
# Override: set `HELLO_DOCTOR_DATABASE_URL` (typically from
# `config/dev.secret.exs`) to point at a Neon dev branch. Several columns on
# shared tables are bot-owned and only exist on Neon (e.g.
# `conversations.quality_signal` / `operator_notes`, bot ADR-019/059), so any
# page that selects them 500s against a local Postgres that hasn't had the
# matching DDL applied. Use the override to get the full bot-owned schema.
if hd_url = System.get_env("HELLO_DOCTOR_DATABASE_URL") do
  IO.puts(:stderr, "[dev.exs] HelloDoctor repo → Neon (#{URI.parse(hd_url).host})")

  config :ledgr, Ledgr.Repos.HelloDoctor,
    url: hd_url,
    ssl: [
      verify: :verify_none,
      server_name_indication: to_charlist(URI.parse(hd_url).host || "")
    ],
    stacktrace: true,
    show_sensitive_data_on_connection_error: true,
    pool_size: 10,
    priv: "priv/repos/hello_doctor"
else
  IO.puts(
    :stderr,
    "[dev.exs] HelloDoctor repo → local Postgres (bot-owned columns like " <>
      "conversations.quality_signal WILL be missing; set HELLO_DOCTOR_DATABASE_URL " <>
      "to use the Neon dev branch)"
  )

  config :ledgr, Ledgr.Repos.HelloDoctor,
    username: "postgres",
    password: "postgres",
    hostname: "localhost",
    database: "ledgr_hello_doctor_dev",
    stacktrace: true,
    show_sensitive_data_on_connection_error: true,
    pool_size: 10,
    priv: "priv/repos/hello_doctor"
end
